### PR TITLE
Updated Dashboard, External CSS File, Filter by Author

### PR DESCRIPTION
**Pull request by grafxflow**
Updated the Dashboard to show the linker post title - Incase 2 link urls (i.e. /go/same-url-V1/ and  /go/same-url-V2/) goto the same url.

Now uses an external CSS file based in the folder (wp-linker/classes/linker-styles).

Can filter by Author on the listings page.

### CODE REVIEW

**Comment by grafxflow** [comment]
Seems to be some conflict with lines of code, but unsure where.

**Comment by KingYes** [comment]
I resolve this later when I merge your code :)

**Comment by grafxflow** [comment]
Cool

**Comment by grafxflow** [comment]
Noticed some conflict with the external css file in the script.

Line 271 needs changing from

```wp_enqueue_style( 'dashboard-widget-styles', plugins_url( '', __FILE__ ) . '/linker-styles.css' );```

to

```wp_enqueue_style( 'linker-dashboard-widget-styles', plugins_url( '', __FILE__ ) . '/linker-styles.css' );```

**Comment by KingYes** [comment]
Well done :)
Thanks.

**Pull request merged**
