### PR TITLE
Create linker-id_ID.po

### PR DESCRIPTION
**Pull request by YiiBooster**
Indonesian Translation for Linker Wordpress plugin

### CODE REVIEW

**Comment by KingYes** [comment]
Thanks :)

**Comment by YiiBooster** [comment]
I cant upload . . . Please download from https://www.dropbox.com/s/p86zh4bnv5e7nzp/id_ID-po-mo-file-for-linker.zip?dl=0

**Comment by KingYes** [comment]
Did you change the `.po` file?

**Comment by YiiBooster** [comment]
No, I dont. all file .po not changed. the story is in the frist time I just can upload .po file. but, i cant upload .mo file. 
so, optionaly I think to archive with .zip packs and upload that file on dropbox to get perfect .po and .mo file.

**Comment by KingYes** [comment]
Merged. Please let's me know what a credit you want in our readme. What is your name?

**Pull request merged**
